# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Portfolio CI

on:
  push:
    branches: [main]

jobs:
  vercel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #  add env file to .env.local

      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: protfolio-theme-1 # project name in Vercel
          envVariableKeys: EMAILJS_USER_ID, TEMPLATE_ID, SERVICE_ID
        env:
          EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}

          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}

          SERVICE_ID: ${{ secrets.SERVICE_ID }}

      # deploy app to vercel
      - name: deploy site to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          envVariableKeys: ""
